name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  wait_for_workflows:
    name: Wait for workflows
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.merge_group.head_sha }}

      - name: Wait for workflows
        uses: smartcontractkit/chainlink-github-actions/utils/wait-for-workflows@fc3e0df622521019f50d772726d6bf8dc919dd38 # v2.3.19
        with:
          max-timeout: '900'
          polling-interval: '30'
          exclude-workflow-names: 'Package Artifact Tests'
          exclude-workflow-ids: ''
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DEBUG: 'true'

  sonarqube:
    name: SonarQube Scan
    needs: [wait_for_workflows]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: ci-sonarqube
        uses: smartcontractkit/.github/actions/ci-sonarqube-ts@42cac739a42c5a56d439772a874b3cd95ee1bdc9 # ci-sonarqube-ts@0.0.0
        with:
          test-report-artifact: "unit-tests-coverage"
          junit-xml-report-paths: "junit.xml"
          typescript-lcov-report-paths: "lcov.info"
          lint-report-artifact: "eslint-report"
          eslint-json-report-paths: "eslint-report.json"
          include-lint: "true"
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
