name: Package Artifact Tests

on:
  pull_request:

jobs:
  test-package-artifacts:
    runs-on: ubuntu-latest
    env:
      DEBUG_TEST_SETUP: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18

      - name: setup-foundry
        uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # v1.3.1

      - name: Install dependencies
        run: npm install # npm install instead of npm ci is used to prevent unsupported platform errors due to the fsevents sub-dependency --no-optional

      - name: Setup Deno
        uses: denoland/setup-deno@041b854f97b325bd60e53e9dc2de9cb9f9ac0cba # v1.1.4
        with:
          deno-version: '1.36.2'

      - name: Build package artifacts
        run: npm run build

      - name: Remove source files
        run: rm -rf src

      - name: Run tests against package artifacts
        run: npm run test:package
